# Generated by Django 5.2.11 on 2026-02-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_records', '0001_initial'),
        ('core', '0002_add_collection_days_labourers_expenses'),
        ('properties', '0002_add_collection_days_labourers_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routeassignment',
            name='collector',
            field=models.ForeignKey(limit_choices_to={'role__name': 'collector'}, on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CasualLabourer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casual_labourer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='GarbageCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField(blank=True, null=True)),
                ('incident_or_dispute', models.TextField(blank=True, help_text='Any dispute or incident during collection')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labourer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='collection_records.casuallabourer')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garbage_collection_logs', to='properties.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage_collection_logs', to='properties.property')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_garbage_logs', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garbage_collection_logs', to='core.zone')),
            ],
            options={
                'ordering': ['-collection_date', '-collection_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourerZoneRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labourer_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('labourer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_rotations', to='collection_records.casuallabourer')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labourer_rotations', to='core.zone')),
            ],
            options={
                'ordering': ['-valid_from', 'zone'],
            },
        ),
    ]
