# Generated by Django 5.2.11 on 2026-02-14 11:13

from django.db import migrations


def create_default_expense_types(apps, schema_editor):
    ExpenseType = apps.get_model('billing', 'ExpenseType')
    ExpenseType.objects.get_or_create(name='Payroll (casual labourers)', defaults={'pay_frequency': 'weekly'})
    ExpenseType.objects.get_or_create(name='Utilities', defaults={'pay_frequency': 'monthly'})
    ExpenseType.objects.get_or_create(name='Maintenance', defaults={'pay_frequency': 'monthly'})
    ExpenseType.objects.get_or_create(name='Other', defaults={'pay_frequency': 'monthly'})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_collection_days_labourers_expenses'),
    ]

    operations = [
        migrations.RunPython(create_default_expense_types, noop),
    ]
