# Generated by Django 5.2.11 on 2026-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True),
        ),
    ]
