# Generated by Django 5.2.11 on 2026-02-14 11:10

from django.db import migrations


def create_casual_labourer_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.get_or_create(
        name='casual_labourer',
        defaults={'description': 'Casual Labourer (rotating; fills collection form)'},
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_casual_labourer_role, noop),
    ]
