# Generated by Django 5.2.11 on 2026-02-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='e.g. Plot 45, House A', max_length=200),
        ),
        migrations.CreateModel(
            name='PropertyCollectionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 6=Sunday. Tuesday=2, Saturday=6.')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_days', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'day_of_week'],
                'unique_together': {('property', 'day_of_week')},
            },
        ),
    ]
