# Generated by Django 5.2.11 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_collection_days_labourers_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='address',
            field=models.TextField(blank=True, help_text='Start typing for address suggestions (exact location on map).'),
        ),
    ]
